### ISSUE TITLE
use bundler instead exposing node_modules

### ISSUE THREAD

**Issue by xhyrom** [oven-sh/setup-bun#10]
# Why

Exposing `node_modules` severely degrades the developer experience, especially the push speed and the ability to contribute.

# Solutions

1. Wait for the new [bun bundler](https://github.com/oven-sh/bun/pull/2312)
2. Use [ncc](https://npmjs.com/@vercel/ncc)

At the moment we'll probably use ncc, since we can't afford to wait for a new bundler, we'll migrate the bundler after the new one.

**Comment by xhyrom** [comment]
cc @Electroid, what do you think?

**Comment by Electroid** [comment]
@xHyroM Bun's bundler is so close that I think it's okay to wait for it. Normally wouldn't want to block, but it's just that close.

**Comment by xhyrom** [comment]
> @xHyroM Bun's bundler is so close that I think it's okay to wait for it. Normally wouldn't want to block, but it's just that close.

Don't know approximately how long, I've already created a PR for ncc. In my opinion we should use ncc and then calmly go straight to bun bundler, it's really horrible to push node_modules even when you have bad internet.

**Comment by xhyrom** [comment]
@Electroid i think we should merge it for now, because i want really implement symlink bunx but i cant because i dont have WSL now and i dont want to overwrite all node_modules etc

**Comment by xhyrom** [comment]
Okay you're right, I'll do it for new bundler :D

**Comment by xhyrom** [comment]
Closed by https://github.com/oven-sh/setup-bun/pull/18
