### ISSUE TITLE
Specifying bun-download-url does not work

### ISSUE THREAD

**Issue by mtsewrs** [oven-sh/setup-bun#104]
Using macos-latest on github action
```
uses: oven-sh/setup-bun@v2
with:
  bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-darwin-x64.zip"
```

This errors with "Error: Downloaded a new version of Bun, but failed to check its version? Try again"

**Comment by xhyrom** [comment]
`macos-latest` cpu is aarch64, not x86. You can also change the url to something like in:
https://github.com/oven-sh/setup-bun/pull/105/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R148

**Comment by mtsewrs** [comment]
Ah it should be aarch64, that makes sense. Thanks I'll try that
