### ISSUE TITLE
Bug: cross-device link not permitted

### ISSUE THREAD

**Issue by DmACKGL** [oven-sh/setup-bun#17]
Executing the job `oven-sh/setup-bun@v1`, the installation fails, returning  `Error: Error: EXDEV: cross-device link not permitted.`

Runner: `self-hosted`
(more ENV details included on the image)
![image](https://github.com/oven-sh/setup-bun/assets/10565361/f52707c6-98fd-49af-a317-748a1f4175c8)

**Comment by floydjones1** [comment]
Hello, I am encountering this issue as well. I am lost 😬 
```sh
Downloading a new version of Bun: https://bun.sh/download/1.0.0/linux/x64?avx2=true&profile=false
/usr/bin/unzip -o -q /runner/_work/_temp/14dfb441-2782-4171-918d-3[5](https://***/actions/runs/331818/jobs/765705#step:3:6)325021b0ea
Error: Error: EXDEV: cross-device link not permitted, rename '/runner/_work/_temp/2b4b2774-c3ef-4e1e-98da-5ddec0038704/bun-linux-x[6](https://***/actions/runs/331818/jobs/765705#step:3:7)4-baseline/bun' -> '/home/runner/.bun/bin/bun'
```

**Comment by xhyrom** [comment]
Should be fixed by https://github.com/oven-sh/setup-bun/commit/67e559db2c8666d0d4455009db7c5ab6378e550f https://github.com/oven-sh/setup-bun/pull/15
