### ISSUE TITLE
404 error for bun in bun actions and project actions

### ISSUE THREAD

**Issue by compilersEllie** [oven-sh/setup-bun#30]
Recently attempted to use bun using this action and got a 404.

Found the same error at the following CI run of the action.
Here:
https://github.com/oven-sh/setup-bun/actions/runs/6315027566/job/17146629315

Log for reference:
```
Run ./
Downloading a new version of Bun: https://bun.sh/download/9be68ac2350b965037f408ce4d47c3b9d9a76b63/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 400
```

**Comment by xhyrom** [comment]
@Electroid

**Comment by xhyrom** [comment]
Should be already fixed (not exactly link you provided because it's already expired)
