### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by Mystogab** [oven-sh/setup-bun#31]
So I'm getting this error:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: oven-sh/setup-bun@v1.
```
And I'm wondering if is it to hard to move to nodejs 20 action?

**Comment by Electroid** [comment]
Should be easy, we'll do it.

**Comment by kmartinezmedia** [comment]
Any update on this?

**Comment by xhyrom** [comment]
> Any update on this?

Latest setup-bun action uses nodejs v20.
