### ISSUE TITLE
404 While downloading a new version of Bun

### ISSUE THREAD

**Issue by kennyvv** [oven-sh/setup-bun#34]
Starting about 30 minutes ago as of nov 17th 14:49 i get an error while using this action. Perhaps you guys changed the download url? Looking forward to hearing from  you!
```
Run oven-sh/setup-bun@v1
Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 404
```

**Comment by SallyBlichG** [comment]
+1

**Comment by guardio-nick** [comment]
We are affected by this as well

**Comment by Jarred-Sumner** [comment]
Are you still seeing this if you retry?

**Comment by SallyBlichG** [comment]
> Are you still seeing this if you retry?

No, it's working now, thanks!

**Comment by kennyvv** [comment]
> Are you still seeing this if you retry?

Seems to be working now, thanks for the quick reply!

**Comment by guardio-nick** [comment]
Thanks! works now
