### ISSUE TITLE
Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by jasongitmail** [oven-sh/setup-bun#35]
This github action is failing with a 404. 

Here's the log
```
Run oven-sh/setup-bun@v1
Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 404
```

I was using:

```yaml
- uses: oven-sh/setup-bun@v1
```

and also tried:

```yaml
- uses: oven-sh/setup-bun@v1
  with:
    bun-version: latest
```

both are failing with the same error.

**Comment by Electroid** [comment]
It should be working again, will investigate why it was flaky.

**Comment by bobmaerten** [comment]
Still flaky... I get `Unexpected end of JSON input` from the generated download URL (1.0.1 ???) https://bun.sh/download/1.0.1/linux/x64?avx2=true&profile=false

**Comment by andriygm** [comment]
using version scheme `bun-v<num>` seems to work e.g. `bun-v1.0.1`

**Comment by exoRift** [comment]
I have the same issue except I get a 400

**Comment by Jarred-Sumner** [comment]
@Electroid can we move this to be a redirect which avoids making any API calls to GitHub?

**Comment by Electroid** [comment]
Updated our API so it no longer depends on the Github API for known versions, such as:
* `latest`, `canary`
* `1.0.0`, `1.0`, `1.0.10`
* `v1.0.10`, `bun-v1.0.10`

It will only check the Github API for:
* `1.0.x`
* `> 1`
* `> 1.1.0`

Please let us know if you still run into any issues, these changes are now live.

**Comment by bobmaerten** [comment]
My builds seem to work again. Thx

**Comment by PabloSzx** [comment]
![image](https://github.com/oven-sh/setup-bun/assets/8672915/f322ce19-0865-4a81-9472-ba63a79124e2)

Is this error expected?

**Comment by PabloSzx** [comment]
I see https://github.com/oven-sh/setup-bun/issues/44

**Comment by xhyrom** [comment]
> ![image](https://private-user-images.githubusercontent.com/8672915/293802545-f322ce19-0865-4a81-9472-ba63a79124e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTg4NjQsIm5iZiI6MTcwNDM1ODU2NCwicGF0aCI6Ii84NjcyOTE1LzI5MzgwMjU0NS1mMzIyY2UxOS0wODY1LTRhODEtOTQ3Mi1iYTYzYTc5MTI0ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMDg1NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFmMDIzNmU3ODg5NGFkZmY1NDU0YjYyNjY3YTMwZmI4ZWI1MTdhOTFlYjBkZDBjYjQ5NWM5YWNmODMwYzI1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vREJmaAy9EIc-b3FUa1MMPYqMCE9q4-E0Ur-pIcgfUw)
> 
> Is this error expected?

This is related to https://github.com/oven-sh/setup-bun/issues/22
