### ISSUE TITLE
Hanging after Cache saved successfully message

### ISSUE THREAD

**Issue by andyexeter** [oven-sh/setup-bun#59]
Hey there,

We've noticed recently that on a cold cache this action hangs for over 2 minutes after the "Cache saved successfully" message. This is probably related to the actions/cache package and the Node version (see https://github.com/actions/setup-node/issues/878)

They solved this by exiting early rather than waiting for the cache save promise to resolve: https://github.com/actions/setup-node/pull/917/files

I propose to implement the same fix here, and also as per the node action moving the cache saving to a **[`runs.post`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost)** hook so it runs after other steps if the workflow was successful e.g. https://github.com/actions/setup-node/blob/25b062c917b0c75f8b47d8469aff6c94ffd89abb/action.yml#L38-L39

I'm happy to create a PR for this.

**Comment by xhyrom** [comment]
If you can, create PR (from watches)
