### ISSUE TITLE
`set-output` is deprecated

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/setup-bun#6]
I started to get this log on my workflows: 
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

Do you think this can fixed easily?

**Comment by xhyrom** [comment]
Yes, I'll look into it today.

**Comment by xhyrom** [comment]
Forgot, today it will be fixed.

**Comment by xhyrom** [comment]
Resolved by 0.1.8
