### ISSUE TITLE
Github Self-Hosted Runners fail with Segmentation fault

### ISSUE THREAD

**Issue by claughinghouse** [oven-sh/setup-bun#61]
When running without the node setup the self-hosted runners image throws a Segmentation Fault error 139 when running any bun commands. 

To resolve I needed to add the node setup step but it would be ideal if this were not needed.

<img width="1092" alt="image" src="https://github.com/oven-sh/setup-bun/assets/2333441/1b407f04-64f4-40df-b8d6-48444534e86d">

This is the workaround until unzip is added to the install list and the error above is identified. 

<img width="953" alt="image" src="https://github.com/oven-sh/setup-bun/assets/2333441/f8fe0985-bc9b-4c01-b3a9-2684698fb263">

**Comment by xhyrom** [comment]
Can you try the latest version of setup-bun please?
