### ISSUE TITLE
It's best for use `actions/tool-cache` not `actions/cache`

### ISSUE THREAD

**Issue by PittyXu** [oven-sh/setup-bun#63]
`actions/tool-cache` is for tools, `actions/cache` is for build.

https://github.com/actions/toolkit/blob/main/packages/tool-cache/README.md

**Comment by xhyrom** [comment]
We're already using `@actions/tool-cache` for downloading, extracting and `@actions/cache` for the actual cache. Other actions do the same thing.

**Comment by PittyXu** [comment]
> We're already using `@actions/tool-cache` for downloading, extracting and `@actions/cache` for the actual cache. Other actions do the same thing.

It can use `@actions/tool-cache` to actual cache, because `@actions/cache` will be cleaned unexpectedly.
