### ISSUE TITLE
403 while Downloading a new version of Bun

### ISSUE THREAD

**Issue by networkhermit** [oven-sh/setup-bun#70]
```text
Run oven-sh/setup-bun@v1
Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx2=true&profile=false
Error: Error: Unexpected HTTP response: 403
```

Does https://bun.sh/download has some kind of WAF or rate limiting mechanism? When I manually run curl on the runner it displayed `<title>Just a moment...</title>` but I coudn't see the reason.

Also I can confirm that directly curl https://github.com/oven-sh/bun/releases/download/bun-v1.0.33/bun-linux-x64-baseline.zip is ok.

P.S. We use self-hosted runners and utilize the cloudflare WARP, but I think it shouldn't be a problem to setup bun.

**Comment by keeganstothert** [comment]
i get the same but with a 404 and only on our windows build environment

**Comment by xhyrom** [comment]
> i get the same but with a 404 and only on our windows build environment

https://github.com/oven-sh/setup-bun/pull/72

**Comment by xhyrom** [comment]
@networkhermit are you still experiencing this issue? If you want to try curl, don't forget to add `-L` as the API redirects directly to github:

```bash
curl -O -L "https://bun.sh/download/latest/linux/x64?avx2=true&profile=false"
```

**Comment by networkhermit** [comment]
> @networkhermit are you still experiencing this issue? If you want to try curl, don't forget to add `-L` as the API redirects directly to github:
> 
> ```shell
> curl -O -L "https://bun.sh/download/latest/linux/x64?avx2=true&profile=false"
> ```

No. We switched to another ci runner group since the 403 error.

I know the `-L` flag of curl, but instead of 302 it got 403 from cloudflare at that time, meaning it could never redirect to github.

We will try to use the previous runner group in the the next few weeks. I will report here once the issue happens again.

**Comment by xhyrom** [comment]
> > @networkhermit are you still experiencing this issue? If you want to try curl, don't forget to add `-L` as the API redirects directly to github:
> > ```shell
> > curl -O -L "https://bun.sh/download/latest/linux/x64?avx2=true&profile=false"
> > ```
> 
> No. We switched to another ci runner group since the 403 error.
> 
> I know the `-L` flag of curl, but instead of 302 it got 403 from cloudflare at that time, meaning it could never redirect to github.
> 
> We will try to use the previous runner group in the the next few weeks. I will report here once the issue happens again.

Okay, great!

**Comment by xhyrom** [comment]
Are you still experiencing this issue?

**Comment by networkhermit** [comment]
No. I think this issue can be closed.

**Comment by Showfom** [comment]
@xhyrom please check the similar issue https://github.com/oven-sh/bun/issues/6305

**Comment by xhyrom** [comment]
This action doesn't depend on bun's download api, so it should be fine. I aso don't have access to it, so there is nothing I can do.
