### ISSUE TITLE
Expand-Archive: is not a supported archive file format. .zip is the only supported archive file format.

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/setup-bun#79]
Using the action on a self-hosted windows runner, I get the following error:

```
Downloading a new version of Bun: https://bun.sh/download/latest/win32/x64?avx2=true&profile=false
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\Users\...\actions-runner\_work\_temp\0bb06b9b-3ec9-438b-9df3-9f6b8f3d6db0' -DestinationPath 'C:\Users\...\actions-runner\_work\_temp\78124392-7335-40f5-bee0-b840781ccc98' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\...\actions-runner\_work\_temp\0bb06b9b-3ec9-438b-9df3-9f6b8f3d6db0', 'C:\Users\...\actions-runner\_work\_temp\78124392-7335-40f5-bee0-b840781ccc98', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\Users\...\actio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
```

The problem seems to be that the action is using powershell 1.0, which does not support expanding the archive, even though I have powershell 7 installed, which should support it.

**Comment by xhyrom** [comment]
what's the version of windows on your runner?

**Comment by itsyoboieltr** [comment]
> what's the version of windows on your runner?

Microsoft Windows NT 10.0.17763.0 x64

**Comment by xhyrom** [comment]
Hmmm, that is version 1809 so it should work fine. Can you try running the `powershell -c "irm bun.sh/install.ps1|iex"` instead of using setup-bun and see if it happens (it should fail)?

**Comment by itsyoboieltr** [comment]
> Hmmm, that is version 1809 so it should work fine. Can you try running the `powershell -c "irm bun.sh/install.ps1|iex"` instead of using setup-bun and see if it happens (it should fail)?

It worked :) it installed bun successfully

**Comment by xhyrom** [comment]
So it's something with the setup-bun action, i'll investigate, thanks for report!

**Comment by itsyoboieltr** [comment]
> So it's something with the setup-bun action, i'll investigate, thanks for report!

Thank you!

**Comment by xhyrom** [comment]
Seems like there's something with https://github.com/oven-sh/setup-bun/blob/77ae1717ed579899022cd44cfe8251a0a1b7acf4/src/action.ts#L123 and https://github.com/actions/toolkit/blob/ae38557bb0dba824cdda26ce787bd6b66cf07a83/packages/io/src/io.ts#L155-L254 in `@actions/io`

Related issue?: https://github.com/actions/toolkit/issues/1179

**Comment by xhyrom** [comment]
Hey, it's harder for me to test this since i don't have windows server. Can you please try the dev version of setup-bun? Put `oven-sh/setup-bun@dev` into `uses`

**Comment by itsyoboieltr** [comment]
> Hey, it's harder for me to test this since i don't have windows server. Can you please try the dev version of setup-bun? Put `oven-sh/setup-bun@dev` into `uses`

it works now! Thank you for the quick fix!
