### ISSUE TITLE
Error when running bun install from Github CI

### ISSUE THREAD

**Issue by blushi** [oven-sh/setup-bun#84]
Since today, `bun install` step is failing in my github workflow with the following error (using oven-sh/setup-bun@v1):

```
  bun install
  shell: /usr/bin/bash -e {0}
bun install v1.1.14 (7c27f3f9)
error: FailedToOpenSocket downloading tarball react-error-overlay@6.0.9
Error: Process completed with exit code 1.
```

**Comment by blushi** [comment]
FYI using `bun-version: 1.1.13` solves the issue temporarily

**Comment by xhyrom** [comment]
This looks like issue with bun itself

**Comment by blushi** [comment]
> This looks like issue with bun itself

Indeed. So closing.
