### ISSUE TITLE
Missing installation urls

### ISSUE THREAD

**Issue by darklight9811** [oven-sh/setup-bun#87]
### What steps can reproduce the bug?

Try to run `https://bun.sh/download/1.1.19/linux/x64?avx2=true&profile=false` (link generated by oven-sh/setup-bun)

### What is the expected behavior?

There are tons of versions missing from the archive, it should find the file and download it

### What do you see instead?

Not found page

### Additional information

Didn't know if I post it here or on bun repository

**Comment by Jarred-Sumner** [comment]
Bun v1.1.19 doesn't exist yet

You probably meant 

`https://bun.sh/download/1.1.9/linux/x64?avx2=true&profile=false`

**Comment by darklight9811** [comment]
@Jarred-Sumner its the version that the cicd action is trying to run, but other versions are missing too

**Comment by Jarred-Sumner** [comment]
What versions are missing?
