### ISSUE TITLE
cache-hit output is always false

### ISSUE THREAD

**Issue by deanrih** [oven-sh/setup-bun#88]
This might be more of a question than an issue/bug report i guess, but I notice that on every Setup Bun step, it will always download the new version, and when I add

```
echo "${{ steps.bun.outputs.cache-hit }}"
echo "${{ steps.bun.outputs.bun-version }}"
echo "${{ steps.bun.outputs.bun-revision }}"
echo "${{ steps.bun.outputs.bun-path }}"
echo "${{ steps.bun.outputs.bun-download-url }}"
```

to another step, it shows for the `cache-hit` is false, so is there some additional configuration I have to do or am I misunderstanding the whole caching for bun version?

![image](https://github.com/user-attachments/assets/76d88842-687c-44b9-9ad4-eda380a58ddf)

Also I guess it doesn't really matter because the Setup Bun process took only 1 second already so not sure if caching would even help

**Comment by xhyrom** [comment]
Caching works only when you pin the bun version. When using "latest", it always downloads the latest possible version and that *could* be cached but isn't.

**Comment by deanrih** [comment]
> Caching works only when you pin the bun version. When using "latest", it always downloads the latest possible version and that _could_ be cached but isn't.

ah, I see, thank you, why didn't I think of that...
