### ISSUE TITLE
Taking a long time to end

### ISSUE THREAD

**Issue by n-ce** [oven-sh/setup-bun#92]
The worflow works well without any errors but it's always stuck for 4-5 minutes on bun after the bun work is done. https://github.com/n-ce/Uma/actions

**Comment by xhyrom** [comment]
> The worflow works well without any errors but it's always stuck for 4-5 minutes on bun after the bun work is done. https://github.com/n-ce/Uma/actions

Can you show some exact example? If you mean `bun xxx.ts`, that's not issue with this action. This action only downloads bun, it doesn't do anything with bun's runtime.

PS: you can do `git commit -m "xxx" || true` and `git push || true`. It'll stop falling if there are no changes 😄

**Comment by n-ce** [comment]
> If you mean `bun xxx.ts`, that's not issue with this action. This action only downloads bun, it doesn't do anything with bun's runtime.

Then why does it hang after the bun work is done. 🤔
The exact part is between `bun main.ts` and `git add .` , which is what I'd call the bun exit period.
On Node, the same workflow resolves within a minute on average.

> PS: you can do `git commit -m "xxx" || true` and `git push || true`. It'll stop falling if there are no changes 😄

Thanks for this, I was looking for it!

**Comment by xhyrom** [comment]
> > If you mean `bun xxx.ts`, that's not issue with this action. This action only downloads bun, it doesn't do anything with bun's runtime.
> 
> Then why does it hang after the bun work is done. 🤔 The exact part is between `bun main.ts` and `git add .` , which is what I'd call the bun exit period. On Node, the same workflow resolves within a minute on average.
> 

Good question, can you try adding process.exit at the end of the code and some simple console.log?

**Comment by n-ce** [comment]
Just noticed https://github.com/n-ce/Uma/actions/runs/10265392177, this has been fixed now since 3 days.

 It completes crazy fast under 30 seconds now compared to 4 mins & 30 seconds.
